version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/development/dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../../.env/.env.development
    restart: always
