// Generated by ts-to-zod
import { z } from 'zod'

export const timestampSchema = z.date()

export const userSchema = z.object({
  id: z.string(),
  name: z.string(),
  pwd: z.string(),
})

export const dbSchema = z.object({
  user: userSchema,
})
