FROM node:22

COPY . /opt/app
WORKDIR /opt/app

RUN corepack enable && \
    pnpm i && \
    export PARCEL_WORKER_BACKEND=process && \
    echo "\n" | npm run db:push:prod

CMD npm run _build:all && npm run run:service:prod
