version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/production/dockerfile
    ports:
      - 80:80
    env_file:
      - ../../.env/.env.production
    restart: always
    volumes:
      - ../../db:/opt/app/db
