FROM node:22

ENV TZ=Asia/Shanghai
COPY . /opt/app
WORKDIR /opt/app

RUN corepack enable && \
    pnpm i --prod && \
    export PARCEL_WORKER_BACKEND=process && \
    npm run _build:all

CMD echo "\n" | npm run db:push:prod && npm run run:service:prod
